#!/bin/bash

########################################################
# Inicia a aplicação DSpace 8 Angular usando PM2
# Autor: Michael Martins 
# Data: 2025-20-05
#########################################################

cd /opt/dspace-8-angular
pm2 delete dspace-angular
pm2 start dist/server/main.js --name dspace-angular

